### PR TITLE
Remove python and related packages

### PR DESCRIPTION
**Pull request by sophiewigmore**
Remove `python` and related packages from the stack to reduce the CVE surface area of the image. Work has been done in the PHP Buildpack to remove reliance on a stack-provided Python installation.

Packages removed:
- `bzr`
- `dh-python`
- `libjson-glib-1.0-0`
- `libmagickwand-dev`
- `libpango1.0-0`
- `mercurial`
- `ubuntu-minimal`

Packages added:
- `netbase` - needed, otherwise the package is omitted
- `tzdata` - needed to prevent the following error during build: 
  ```
  #9 275.1 Generation complete.
  #9 275.1 dpkg-query: package 'tzdata' is not installed and no information is available
  #9 275.1 Use dpkg --info (= dpkg-deb --info) to examine archive files.
  #9 275.1 /usr/sbin/dpkg-reconfigure: tzdata is not installed
  ```
<details>
<summary>Packages in the final receipt that were removed as a result of these changes:</summary>

- `apt-utils`
- `automake`
- `autotools-dev`
- `brz`
- `bzr`
- `console-setup`
- `console-setup-linux`
- `debconf-i18n`
- `dh-python`
- `distro-info`
- `distro-info-data`
- `eject`
- `gir1.2-freedesktop:amd64`
- `gir1.2-gdkpixbuf-2.0:amd64`
- `gir1.2-glib-2.0:amd64`
- `gir1.2-rsvg-2.0:amd64`
- `init`
- `iputils-ping`
- `isc-dhcp-client`
- `kbd`
- `keyboard-configuration`
- `kmod`
- `less`
- `libapparmor1:amd64`
- `libblkid-dev:amd64`
- `libbz2-dev:amd64`
- `libcairo-script-interpreter2:amd64`
- `libcairo2-dev:amd64`
- `libcryptsetup12:amd64`
- `libdevmapper1.02.1:amd64`
- `libdjvulibre-dev:amd64`
- `libdjvulibre-text`
- `libdjvulibre21:amd64`
- `libdns-export1110`
- `libexif-dev:amd64`
- `libexif12:amd64`
- `libgdk-pixbuf-2.0-dev:amd64`
- `libgdk-pixbuf2.0-bin`
- `libgirepository-1.0-1:amd64`
- `libglib2.0-bin`
- `libglib2.0-data`
- `libglib2.0-dev-bin`
- `libglib2.0-dev:amd64`
- `libilmbase-dev:amd64`
- `libilmbase25:amd64`
- `libip4tc2:amd64`
- `libisc-export1105:amd64`
- `libjson-glib-1.0-0:amd64`
- `libjson-glib-1.0-common`
- `libkmod2:amd64`
- `liblcms2-dev:amd64`
- `liblqr-1-0-dev:amd64`
- `libltdl-dev:amd64`
- `liblzo2-2:amd64`
- `libmagickcore-6-arch-config:amd64`
- `libmagickcore-6-headers`
- `libmagickcore-6.q16-6-extra:amd64`
- `libmagickcore-6.q16-dev:amd64`
- `libmagickwand-6-headers`
- `libmagickwand-6.q16-dev:amd64`
- `libmagickwand-dev`
- `libmount-dev:amd64`
- `libnetplan0:amd64`
- `libnewt0.52:amd64`
- `libopenexr-dev`
- `libopenexr25:amd64`
- `libopenjp2-7-dev:amd64`
- `libpango1.0-0:amd64`
- `libpangoxft-1.0-0:amd64`
- `libpcre16-3:amd64`
- `libpcre3-dev:amd64`
- `libpcre32-3:amd64`
- `libpcrecpp0v5:amd64`
- `libpixman-1-dev:amd64`
- `libpython3-stdlib:amd64`
- `librsvg2-common:amd64`
- `librsvg2-dev:amd64`
- `libslang2:amd64`
- `libtext-charwidth-perl`
- `libtext-iconv-perl`
- `libtext-wrapi18n-perl`
- `libwmf-0.2-7:amd64`
- `libwmf-dev`
- `libwmflite-0.2-7:amd64`
- `libxcb-render0-dev:amd64`
- `libxcb-shm0-dev:amd64`
- `libxext-dev:amd64`
- `libxft2:amd64`
- `libxrender-dev:amd64`
- `lsb-release`
- `mercurial`
- `mercurial-common`
- `netcat-openbsd`
- `netplan.io`
- `python-apt-common`
- `python3`
- `python3-apt`
- `python3-breezy`
- `python3-certifi`
- `python3-configobj`
- `python3-distutils`
- `python3-dulwich`
- `python3-fastbencode`
- `python3-lib2to3`
- `python3-minimal`
- `python3-netifaces:amd64`
- `python3-patiencediff`
- `python3-pkg-resources`
- `python3-six`
- `python3-urllib3`
- `python3-yaml`
- `python3.10`
- `python3.10-minimal`
- `sudo`
- `systemd`
- `systemd-sysv`
- `ubuntu-advantage-tools`
- `ubuntu-minimal`
- `udev`
- `vim-common`
- `vim-tiny`
- `whiptail`
- `xkb-data`
- `xxd`
</details>

### CODE REVIEW

**Comment by sophiewigmore** [comment]
Also requesting @robdimsdale

**Comment by robdimsdale** [comment]
Scanning through this list of packages I think it looks ok. I'm a little unsure about some packages (e.g. the various `glib` and `libpcre` packages) but I think they're all ok.

I'm happy to start with this and see if it causes any integration test failures in the buildpacks.

**Review by robdimsdale — APPROVED** [review]

**Comment by robdimsdale** [comment]
I guess, @ryanmoran , that depends on whether our goal is to minimize the difference between bionic and jammy, or minimize the surface area of the jammy stack before we lock in the list of packages. Both are valid outcomes - I think it just depends on what our priorities are.

Using the example you gave, I'm not sure why `apt-utils` would be desired on a stack. I believe that the Cloudfoundry buildpacks don't use it to install or interrogate the system, and I don't know if we support end users / applications doing the same.

It might be safer in terms of customer experience to minimize the difference between the bionic and jammy stacks, but it would lock us into a larger surface area for the lifetime of the stack

**Comment by sophiewigmore** [comment]
@ryanmoran @robdimsdale I'm open to adding as much back to the stack as we can. 
I see your point Rob, but we've been shipping the stack with these packages present up until now, and would be removing them (~120 packages) with little to no explanation that could have downstream side effects. I think I'd rather err on the side of caution and add back whatever we can.

If we later wanted to do a bigger investigation into all of the things we can safely take out in order to reduce the surface areas of the stack I'd be open to that - but I'd rather do the research and be more intentional with it if we can

**Comment by sophiewigmore** [comment]
`ubuntu-advantage-tools`
ubuntu-advantage-tools Depends python3-apt
ubuntu-advantage-tools Depends python3-pkg-resources

`netplan.io`
netplan.io Depends python3
python3    PreDepends python3-minimal
netplan.io Depends python3-netifaces
netplan.io Depends python3-yaml
python3    Depends python3.10
python3.10 Depends python3.10-minimal

`brz`
brz Depends python3-breezy (<= 3.2.1+bzr7585-1build1.1~)
python3-breezy  Depends python3-dulwich
python3-dulwich Depends python3-certifi
python3-breezy Depends python3-configobj
python3-breezy Depends python3-fastbencode
python3-breezy Depends python3-patiencediff
python3-breezy Depends python3-six
python3-dulwich Depends python3-urllib3

`libmagickwand-6.q16-dev`
libmagickwand-6.q16-dev Depends libmagickcore-6.q16-dev
libmagickcore-6.q16-dev Depends librsvg2-dev
librsvg2-dev Depends libglib2.0-dev
libglib2.0-dev Depends libglib2.0-dev-bin
libglib2.0-dev-bin Depends python3-distutils
python3-distutils  Depends python3-lib2to3

**Comment by sophiewigmore** [comment]
@robdimsdale @ryanmoran 

This is the final set of packages removed from the package receipt
- `brz`
- `bzr`
- `dh-python`
- `gir1.2-gdkpixbuf-2.0:amd64`
- `libboost-iostreams1.74.0:amd64`
- `libboost-regex1.74.0:amd64`
- `libcairo-script-interpreter2:amd64`
- `libcairo2-dev:amd64`
- `libcurl4-openssl-dev:amd64`
- `libgdk-pixbuf-2.0-dev:amd64`
- `libgdk-pixbuf2.0-bin`
- `libgirepository-1.0-1:amd64`
- `libglib2.0-bin`
- `libglib2.0-data`
- `libglib2.0-dev-bin`
- `libglib2.0-dev:amd64`
- `libjson-glib-1.0-0:amd64`
- `libjson-glib-1.0-common`
- `liblog-message-simple-perl`
- `libmagickcore-6-arch-config:amd64`
- `libmagickcore-6-headers`
- `libmagickcore-6.q16-6-extra:amd64`
- `libmagickcore-6.q16-6:amd64`
- `libmagickcore-6.q16-dev:amd64`
- `libmagickwand-6-headers`
- `libmagickwand-6.q16-6:amd64`
- `libmagickwand-6.q16-dev:amd64`
- `libmagickwand-dev`
- `libmariadb-dev-compat:amd64`
- `libopenblas-pthread-dev:amd64`
- `libopenblas0-pthread:amd64`
- `libpango1.0-0:amd64`
- `libpangoxft-1.0-0:amd64`
- `libpthread-stubs0-dev:amd64`
- `libpython3.10-minimal:amd64`
- `libpython3.10-stdlib:amd64`
- `librsvg2-common:amd64`
- `librsvg2-dev:amd64`
- `libsasl2-modules-gssapi-mit:amd64`
- `libsource-highlight-common`
- `lsb-release`
- `mercurial`
- `mercurial-common`
- `netplan.io`
- `python-apt-common`
- `python3`
- `python3-apt`
- `python3-breezy`
- `python3-certifi`
- `python3-configobj`
- `python3-distutils`
- `python3-dulwich`
- `python3-fastbencode`
- `python3-lib2to3`
- `python3-minimal`
- `python3-netifaces:amd64`
- `python3-patiencediff`
- `python3-pkg-resources`
- `python3-six`
- `python3-urllib3`
- `python3-yaml`
- `python3.10`
- `python3.10-minimal`
- `ubuntu-advantage-tools`
- `ubuntu-minimal`

**Review by robdimsdale — APPROVED** [review]
I think this looks reasonable. There's a couple of removed libraries that could be a concern (e.g. `libmariadb-dev-compat`) but I think it'll be fine if we have suitable replacements (e.g. `libmariadb-dev`) still on the stack.

At this point I think we should merge this PR, build the stack, and validate it against the existing supported surface area (i.e. CATS).

**Review by robdimsdale — APPROVED** [review]

**Review by ryanmoran — APPROVED** [review]

**Pull request merged**
